"""initial_tables

Revision ID: f738311b1212
Revises: 
Create Date: 2026-09-24 17:52:33.079283

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f738311b1212'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('model_name', sa.Enum('triage', 'disease', 'nutrient', 'sensor', name='modelnameenum'), nullable=False),
    sa.Column('version', sa.Text(), nullable=False),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('retraining_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('model_name', sa.Text(), nullable=False),
    sa.Column('old_metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('new_metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('passed_gate', sa.Boolean(), nullable=False),
    sa.Column('deployed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('farmer', 'admin', name='roleenum'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('farms',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('soil_type', sa.Enum('sandy_loam', 'clay', 'loam', 'silt_loam', name='soiltypeenum'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('checkins',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('farm_id', sa.UUID(), nullable=False),
    sa.Column('image_path', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sensor_readings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('farm_id', sa.UUID(), nullable=False),
    sa.Column('soil_moisture', sa.Float(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('humidity', sa.Float(), nullable=False),
    sa.Column('leaf_wetness', sa.Float(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.Enum('simulated', 'real', name='sourceenum'), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('predictions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('checkin_id', sa.UUID(), nullable=False),
    sa.Column('reading_id', sa.UUID(), nullable=True),
    sa.Column('triage_result', sa.Text(), nullable=False),
    sa.Column('disease_label', sa.Text(), nullable=True),
    sa.Column('disease_conf', sa.Float(), nullable=True),
    sa.Column('sensor_label', sa.Text(), nullable=True),
    sa.Column('sensor_conf', sa.Float(), nullable=True),
    sa.Column('nutrient_label', sa.Text(), nullable=True),
    sa.Column('nutrient_conf', sa.Float(), nullable=True),
    sa.Column('severity', sa.Text(), nullable=True),
    sa.Column('recommendation', sa.Text(), nullable=True),
    sa.Column('model_versions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['checkin_id'], ['checkins.id'], ),
    sa.ForeignKeyConstraint(['reading_id'], ['sensor_readings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alerts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('prediction_id', sa.UUID(), nullable=False),
    sa.Column('farm_id', sa.UUID(), nullable=False),
    sa.Column('severity', sa.Text(), nullable=False),
    sa.Column('channel', sa.Enum('app', 'sms', name='channelenum'), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),
    sa.ForeignKeyConstraint(['prediction_id'], ['predictions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feedback',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('prediction_id', sa.UUID(), nullable=False),
    sa.Column('accurate', sa.Boolean(), nullable=False),
    sa.Column('useful', sa.Boolean(), nullable=True),
    sa.Column('correct_label', sa.Text(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['prediction_id'], ['predictions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('feedback')
    op.drop_table('alerts')
    op.drop_table('predictions')
    op.drop_table('sensor_readings')
    op.drop_table('checkins')
    op.drop_table('farms')
    op.drop_table('users')
    op.drop_table('retraining_jobs')
    op.drop_table('model_versions')
    # ### end Alembic commands ###
